#!/bin/bash

get_block () {
    BLOCK=`od -A n -t u8 -N 1024 -w8 /dev/urandom`
    echo "$BLOCK" | while read -r line
    do
        echo -n "${line:4:20}"
    done
}

N=""
DIGITS="${1:-1}"

while (( ${#N} < $DIGITS )); do
    R=`get_block`
    N="$N$R"
done

echo "${N:0:$DIGITS}"
